version: "3.8"
services:
  web:
    container_name: go-dev
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8000:8000"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    command: /dlv --headless --listen=:40000 --api-version=2 exec /server