version: "3.9"
services:
  web:
    container_name: go-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: $target
      args:
        GO_VERSION: 19.2
    image: go-dev:19.2-${target}
    ports:
      - "8000:8000"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./app:/app
    tty: true